BOARD ?= esp8266-esp-12x
RIOTBASE ?= riot
DEVELHELP ?= 1
QUIET ?= 1

APPLICATION = robodrive
APPDIR = src

USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += esp_wifi

include $(RIOTBASE)/Makefile.include
